---
- name: Ensure folder structure and permissions
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ bitwarden_user }}"
    group: "{{ bitwarden_user }}"
    mode: '0700'
  loop:
    - "{{ bitwarden_user_home }}"
    - "{{ bitwarden_user_home }}/.ssh"

- name: Generate SSH keypair
  ansible.builtin.openssh_keypair:
    path: "{{bitwarden_user_home}}/.ssh/id_ed25519"
    size: 4096
    type: ed25519
    owner: bitwarden
    group: bitwarden
    mode: '0600'

- name: Public key copy
  ansible.builtin.command: "cat {{ bitwarden_user_home }}/.ssh/id_ed25519.pub"
  register: public_key

- name: Set facts
  ansible.builtin.set_fact:
    public_key: "{{ public_key.stdout }}"